version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/InMemoryDatabase

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install pipenv
            pipenv install
            pipenv shell
